ALTER TABLE IF EXISTS public.user_preferences
ADD COLUMN IF NOT EXISTS creator_type TEXT,
ADD COLUMN IF NOT EXISTS content_focus TEXT,
ADD COLUMN IF NOT EXISTS growth_stage TEXT,
ADD COLUMN IF NOT EXISTS target_audience TEXT,
ADD COLUMN IF NOT EXISTS platforms TEXT[],
ADD COLUMN IF NOT EXISTS city TEXT;
